#!/usr/bin/python
# -*- coding:utf-8 -*-

import SH1106
import time
import config
import traceback
import os, sys, subprocess

from PIL import Image,ImageDraw,ImageFont

myconf = "/home/pi/oled/RaspberryPi/python3/wallet.conf"
pktdconf = "/home/pi/.pktd/pktd.conf"
walletconf = "/home/pi/.pktwallet/pktwallet.conf"
balanceFile = "/home/pi/.pktd/pktbalance"
balance = 0

#if os.path.isfile(balanceFile):
#    fd = os.open(balanceFile, os.O_RDONLY)

ready = True

if os.path.isfile(myconf):
    ip="192.168.178.128"

if not os.path.isfile(pktdconf):
    ready = False
    print("no cfg")

if not os.path.isfile(walletconf):
    ready = False
    print("no wallet")

if not os.path.isfile(balanceFile):
    ready = False
    print("no balance file")

if ready:
    #try:
        #/home/pi/pktd/bin/pktd
        #/home/pi/pktd/bin/pktwallet --pkt
        pipe = subprocess.Popen(
            ["/home/pi/pktd/bin/pktctl", "--wallet", "getbalance"],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE
        )
        res = pipe.communicate()

        if(pipe.returncode == 0):
            output = res[0]
            print("BALANCE: " + str(balance))

        if(pipe.returncode != 0):
            error = res[1].decode('utf-8')
            print("ERROR READING BALANCE:\n\n" + error)

        #stream = os.popen('/home/pi/pktd/bin/pktctl --wallet getbalance')
        #output = stream.read()
        #print(output)
        #balance = output
    #except IOError as e:
    #    print(e)

#print("BALANCE: " + str(balance))

try:
    disp = SH1106.SH1106()

    #print("\r\1.3inch OLED")
    # Initialize library.
    disp.Init()
    # Clear display.
    disp.clear()

    # Create blank image for drawing.
    image1 = Image.new('1', (disp.width, disp.height), "WHITE")
    draw = ImageDraw.Draw(image1)
    #font = ImageFont.truetype('Arial.ttf', 20)
    #font10 = ImageFont.truetype('Font.ttf',13)
    font = ImageFont.truetype("/usr/share/fonts/truetype/freefont/FreeMono.ttf", 20)
    font10 = ImageFont.truetype("/usr/share/fonts/truetype/freefont/FreeMono.ttf", 13)

    #print ("***draw line")
    draw.line([(0,0),(127,0)], fill = 0)
    draw.line([(0,0),(0,63)], fill = 0)
    draw.line([(0,63),(127,63)], fill = 0)
    draw.line([(127,0),(127,63)], fill = 0)
    #print ("***draw rectangle")

#    ret = os.read(fd,12)
 #   print(ret)

    #balance = os.system('~/pktd/bin/pktctl --wallet getbalance > ~/.pktd/pktbalance')
#    print(balance)

    ##print ("***draw text")
    draw.text((20,0), 'WALLET', font = font10, fill = 0)
    draw.text((20,20), str(balance)+u' PKT', font = font, fill = 0)

    # image1=image1.rotate(180)
    disp.ShowImage(disp.getbuffer(image1))
    time.sleep(2)

    #print ("***draw image")
    #Himage2 = Image.new('1', (disp.width, disp.height), 255)  # 255: clear the frame
    #bmp = Image.open('pic.bmp')
    #Himage2.paste(bmp, (0,5))
    # Himage2=Himage2.rotate(180)
    #disp.ShowImage(disp.getbuffer(Himage2))
 ##   os.close(fd)

except IOError as e:
    print(e)

except KeyboardInterrupt:
    print("ctrl + c:")
    epdconfig.module_exit()
    exit()
